### ISSUE TITLE
mail_room periodically gets stuck communicating with IMAP servers

### ISSUE THREAD

**Issue by stanhu** [tpitale/mail_room#61]
This stems from a GitLab issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/13357

It seems a number of users are having issues with mail_room getting stuck and not processing any messages. gdb backtraces are available in the notes. 

It looks like there may be two issues here with Ruby's Net::IMAP implementation:

1. May block indefinitely in connect(): https://github.com/rubysl/rubysl-net-imap/blob/2.0/lib/rubysl/net/imap/imap.rb#L1454
2. May sit indefinitely in IDLE state, waiting for messages that never arrive

You can replicate the first problem by just pointing mail_room to a local server on port 5000 by running nc -l 127.0.0.1 5000. It just sits there. 

Regarding the second case, it looks like Ruby 2.3 added a timeout parameter to the [idle method](http://ruby-doc.org/stdlib-2.3.0/libdoc/net/imap/rdoc/Net/IMAP.html#method-i-idle) perhaps to help avoid this issue. We're using Ruby 2.1 now and won't be at 2.3 for some time. 

I can see a couple of solutions that would help:

1. Use/fork a different IMAP client (one that has stricter timeouts)
2. Add a thread to monitor status of IMAP threads (e.g. ping occasionally, retry IDLE command, etc.)
3. Enable TCP keepalives
4. Monkey-patching IMAP socket?

Thoughts?

**Comment by tpitale** [comment]
We can set low-level socket timeouts if we could get proper access to the underlying socket. I'm investigating.

http://www.mikeperham.com/2009/03/15/socket-timeouts-in-ruby/

**Comment by tpitale** [comment]
Looks like setting those socket options probably won't help us without drastic changes to imap anyway (since they use TCPSocket#open in the initializer).

**Comment by tpitale** [comment]
The problem with both connect and idle in pre-2.3 ruby is that they simply don't use timeouts. The only change to 2.3 was passing the timeout to `wait` here: https://github.com/rubysl/rubysl-net-imap/blob/2.0/lib/rubysl/net/imap/imap.rb#L922

**Comment by tpitale** [comment]
We already have a monitoring thread that keeps connections alive passed the 30 minute mark that IMAP would normally disconnect.

I think it could be altered to support suggestion 2.

**Comment by tpitale** [comment]
@stanhu Have you opened issues for any of this with Ruby?

**Comment by tpitale** [comment]
To fix the idle timeout, I'm going to backport the idle method from 2.3 into mail_room.

**Comment by tpitale** [comment]
@stanhu @DouweM Would you like the idle timeout to be configurable?

**Comment by stanhu** [comment]
@tpitale Thanks for looking into this. I think a configurable idle timeout makes sense with a reasonable default.

**Comment by tpitale** [comment]
I'm setting the default to what @DouweM had set the timeout_thread to sleep for, because anything larger will cause the imap server to disconnect. For most users this will present no change in behavior.

**Comment by tpitale** [comment]
I'm not sure we can solve the `connect` issue without some really terrible hacks.

Really, the imap library should be using `connect_nonblock`. But to make that change by subclassing would be a nightmare to maintain, and would likely introduce many more bugs than we would be fixing.

I'll keep thinking about this.

**Comment by stanhu** [comment]
@tpitale Thanks for the latest changes. I think the backport will help a number of users. Can you push out a new release with this?

**Comment by tpitale** [comment]
Released v0.7.0 @stanhu.

**Comment by stanhu** [comment]
Thanks, @tpitale!

**Comment by gdmalet** [comment]
I just put a fairly detailed report into Gitlab CE [issue 13357](https://gitlab.com/gitlab-org/gitlab-ce/issues/13357) of the IDLE timeout not working in a version of mail_room that I think should be okay. This is while talking to a Cyrus IMAP server, which follows the [RFC 2177](https://tools.ietf.org/html/rfc2177) suggestion, and will shut an idle connection after 30 minutes:

> clients using IDLE are advised to terminate the IDLE and
> re-issue it at least every 29 minutes to avoid being logged off.

Is this perhaps a problem with way Gitlab is using mail_room, or could it be a problem with the latter?

**Comment by tpitale** [comment]
Which version of mail_room are you _actually_ using?

**Comment by gdmalet** [comment]
@tpitale Are you suggesting I can't really trust my Gemfile? I'm pretty clueless when it comes to Ruby I'm afraid, but I see this, when `$PWD` is the `vendor` dir at the root of our Gitlab install:
```
# find . -name mail_room\*
./bundle/ruby/2.3.0/specifications/mail_room-0.6.1.gemspec
./bundle/ruby/2.3.0/gems/mail_room-0.6.1
./bundle/ruby/2.3.0/gems/mail_room-0.6.1/bin/mail_room
./bundle/ruby/2.3.0/gems/mail_room-0.6.1/mail_room.gemspec
./bundle/ruby/2.3.0/gems/mail_room-0.6.1/lib/mail_room
./bundle/ruby/2.3.0/gems/mail_room-0.6.1/lib/mail_room.rb
./bundle/ruby/2.3.0/bin/mail_room
./bundle/ruby/2.3.0/cache/mail_room-0.6.1.gem
```
And our Ruby is:
```
# su - gitlab -c "ruby --version"
ruby 2.3.2p113 (2016-04-26 revision 54786) [x86_64-linux]
```
The `bundle install` from the [upgrade docs](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/8.6-to-8.7.md) runs clean....

Does that confirm 0.6.1?

**Comment by tpitale** [comment]
There is a version 0.7.0 of mail_room which may contain the fix you're looking for.

**Comment by gdmalet** [comment]
@tpitale In the morning I'll see if I can work out how to install 0.7.0 on our test server. I've just noticed something odd though, and am still to decide what it means..... This from the logs on the Gitlab server, where `init` is now watching for `mail_room` exiting, and starting a new one:
```
May 11 19:05:26 hub init: gitlab_mail_room main process ended, respawning
May 11 19:34:27 hub init: gitlab_mail_room main process ended, respawning
May 11 20:03:28 hub init: gitlab_mail_room main process ended, respawning
May 11 20:32:30 hub init: gitlab_mail_room main process ended, respawning
May 11 21:01:31 hub init: gitlab_mail_room main process ended, respawning
May 11 21:30:32 hub init: gitlab_mail_room main process ended, respawning
```
Those times are 29 minutes apart, not 30, yet the IMAP server is definitely logging the "idle too long" message after 30 minutes. It seems as if mail_room is getting `ECONNRESET` one minute *before* the IMAP server gives up (? I think), yet IMAP is presumably not noticing what I would think is a closed socket. I'm a bit confused so will ponder this more and report back if I find anything.

Thanks for the response.

**Comment by tpitale** [comment]
You'll probably need to change the Gemfile. `~>` in your example will restrict to anything like 0.6.x. You'd have to change it to `~> 0.7.0` or just `0.7.0` or `>= 0.7.0`. That said, I've got no idea how that works with gitlab.

**Comment by gdmalet** [comment]
@tpitale upgrading to mail_room 0.7.0 did not fix my problems. However, I haven't worked out what's going on with the 29 minutes between restarts I commented on above, so something else could be messing this up. I'll keep hunting. Thanks!

**Comment by tpitale** [comment]
@gdmalet It's possible the error you're receiving still needs to be added to https://github.com/tpitale/mail_room/blob/master/lib/mail_room/mailbox_watcher.rb#L135

I'll need more of that backtrace to determine if that's the case. Either way, it's probably a new issue.

Would you mind opening that?

**Comment by godfat** [comment]
@tpitale Hi, I am investigating this for a few days now, and finally got some kind of conclusion. No solution yet, but somehow a progress. The summary of the process was located at: https://gitlab.com/gitlab-org/gitlab-ce/issues/13357#note_12443913

But the current conclusion is, it seems whenever mail_room got stuck with Google IMAP (I didn't test with any other IMAP), it's actually failing for every attempts for `UID SEARCH`. Logging in, setting inbox, everything else worked. But whenever it tried to `UID SEARCH`, it would fail with an exception. For now, that exception was always: `#<OpenSSL::SSL::SSLError: SSL_write: bad write retry>`.

Do you have any idea what was causing this?

P.S. I was running a modified version of mail_room for testing this: https://github.com/godfat/mail_room/commit/a93aca1cbd94074e2397e6ca429c9d020e4a56bf When this "stuck" happens, the original version of mail_room would go `IDLE` first, and whenever next time it tried to `UID SEARCH`, it would also raise an exception causing mail_room to reset itself, and then `IDLE`, and go on forever. That is, it should be seeing the same issue, that is `UID SEARCH` would always raise an exception and cannot be processed successfully.

**Comment by tpitale** [comment]
Let me know if the `handler` reset ends up not fixing the issue. I think at this point, we shouldn't keep adding to this particular issue as it covers too many varied discussions.

**Comment by godfat** [comment]
I haven't done the final examination, but I believe it has fixed the hanging issue. However, it would miss one mail during reset and setup, therefore I applied another patch, located here:

https://github.com/godfat/mail_room/pull/2

I am not yet 100% sure, but after this patch, it seems it's not missing mails during reset and setup. If you're ok with this change, I think it's good to also merge this.

**Comment by tpitale** [comment]
I'll have to look deeper into this. I think my watcher/handler refactoring will correct that issue.

Essentially, the message should not be marked/deleted/whatever unless delivery was a success.

If process_mailbox isn't after the idle, then we could (theoretically) receive a message and stop running without processing.

**Comment by godfat** [comment]
Looking forward to it :) Thanks for the work.

**Comment by stanhu** [comment]
Thanks, @tpitale and @godfat!

**Comment by godfat** [comment]
I could confirm that https://github.com/godfat/mail_room/pull/2 does fix the issue, and now I am going to try https://github.com/tpitale/mail_room/pull/73

**Comment by tpitale** [comment]
Just released v0.8.0.

**Comment by godfat** [comment]
I believe this should be fixed by #73

**Comment by madsheep** [comment]
Hi guys,
I know this is an old one but just wanted to point out that in ruby trunk we finally get Imap with proper timeout on socket when connecting to the server: 

https://github.com/ruby/ruby/blob/trunk/lib/net/imap.rb#L1132

Just wanted to share good news in case you missed it :)

**Comment by nakilon-idwell** [comment]
@madsheep can you tell which minimal version of Ruby I need for `open_timeout`? Is it in Ruby 2.3?
